// <auto-generated />
using System;
using AdresAdquisition.Infraestructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdresAdquisition.Infraestructure.Migrations
{
    [DbContext(typeof(AdresContext))]
    [Migration("20240629214421_third")]
    partial class third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdresAdquisition.Domain.Entities.Adquisicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Documentacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAdquisicion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoBien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Adquisiciones");

                    b.HasData(
                        new
                        {
                            Id = 812051848,
                            Cantidad = 1,
                            Documentacion = "Docu1",
                            Estado = true,
                            FechaAdquisicion = new DateTime(2024, 6, 29, 21, 44, 21, 409, DateTimeKind.Utc).AddTicks(8502),
                            Presupuesto = 1000m,
                            Proveedor = "Proveedor1",
                            TipoBien = "Bien 1",
                            Unidad = "Unidad 1",
                            ValorTotal = 1000m,
                            ValorUnitario = 1000m
                        },
                        new
                        {
                            Id = 37799617,
                            Cantidad = 2,
                            Documentacion = "Docu1",
                            Estado = true,
                            FechaAdquisicion = new DateTime(2024, 6, 29, 21, 44, 21, 409, DateTimeKind.Utc).AddTicks(8566),
                            Presupuesto = 2000m,
                            Proveedor = "Proveedor1",
                            TipoBien = "Bien 2",
                            Unidad = "Unidad 2",
                            ValorTotal = 2000m,
                            ValorUnitario = 1000m
                        },
                        new
                        {
                            Id = 2040437846,
                            Cantidad = 3,
                            Documentacion = "Docu1",
                            Estado = true,
                            FechaAdquisicion = new DateTime(2024, 6, 29, 21, 44, 21, 409, DateTimeKind.Utc).AddTicks(8570),
                            Presupuesto = 3000m,
                            Proveedor = "Proveedor1",
                            TipoBien = "Bien 3",
                            Unidad = "Unidad 3",
                            ValorTotal = 3000m,
                            ValorUnitario = 1000m
                        },
                        new
                        {
                            Id = 656766761,
                            Cantidad = 4,
                            Documentacion = "Docu1",
                            Estado = true,
                            FechaAdquisicion = new DateTime(2024, 6, 29, 21, 44, 21, 409, DateTimeKind.Utc).AddTicks(8572),
                            Presupuesto = 4000m,
                            Proveedor = "Proveedor1",
                            TipoBien = "Bien 4",
                            Unidad = "Unidad 4",
                            ValorTotal = 4000m,
                            ValorUnitario = 1000m
                        },
                        new
                        {
                            Id = 969837664,
                            Cantidad = 5,
                            Documentacion = "Docu1",
                            Estado = true,
                            FechaAdquisicion = new DateTime(2024, 6, 29, 21, 44, 21, 409, DateTimeKind.Utc).AddTicks(8574),
                            Presupuesto = 5000m,
                            Proveedor = "Proveedor1",
                            TipoBien = "Bien 5",
                            Unidad = "Unidad 5",
                            ValorTotal = 5000m,
                            ValorUnitario = 1000m
                        },
                        new
                        {
                            Id = 560044487,
                            Cantidad = 4,
                            Documentacion = "Docu1",
                            Estado = true,
                            FechaAdquisicion = new DateTime(2024, 6, 29, 21, 44, 21, 409, DateTimeKind.Utc).AddTicks(8579),
                            Presupuesto = 6000m,
                            Proveedor = "Proveedor1",
                            TipoBien = "Bien 6",
                            Unidad = "Unidad 6",
                            ValorTotal = 4000m,
                            ValorUnitario = 1000m
                        });
                });

            modelBuilder.Entity("AdresAdquisition.Infraestructure.Models.LogHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Event")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogHistoricos");
                });
#pragma warning restore 612, 618
        }
    }
}
